# Generated by Django 2.0.7 on 2020-05-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vmi_index', models.DecimalField(decimal_places=2, max_digits=4)),
                ('engineoil_index', models.DecimalField(decimal_places=2, max_digits=4)),
                ('oilfilter_index', models.DecimalField(decimal_places=2, max_digits=4)),
                ('sparkplug_index', models.DecimalField(decimal_places=2, max_digits=4)),
                ('fuelfilter_index', models.DecimalField(decimal_places=2, max_digits=4)),
                ('airfilter_index', models.DecimalField(decimal_places=2, max_digits=4)),
                ('tyre_index', models.DecimalField(decimal_places=2, max_digits=4)),
                ('brakefluid_index', models.DecimalField(decimal_places=2, max_digits=4)),
                ('coolant_index', models.DecimalField(decimal_places=2, max_digits=4)),
                ('battery_index', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
